version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
      - 9100:9100
    links:
      - kafka
      - mysql
    volumes:
      - ./padogrid:/padogrid/
    environment:
      - KAFKA_DEBUG=true
      - JAVA_DEBUG_PORT=9100
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_PLUGIN_PATH=/kafka/connect,/padogrid/plugins,/padogrid/lib
      - CLASSPATH=/padogrid/plugins/*:/padogrid/lib/*
  hive:
    image: javapark07/hive:${HIVE_VERSION}-derby
    ports:
      - 10000:10000
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

networks:
  default:
    external:
      name: my_network
