#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

PORT=8443


if [ ! -d $APP_DIR/padogrid/nifi/data ]; then
  mkdir $APP_DIR/padogrid/nifi/data/json
fi
docker run --rm -d --name nifi -p $PORT:8443 \
  --network debezium_ksql_kafka_default \
  --volume $APP_DIR/padogrid:/padogrid/ \
  apache/nifi:latest

echo "NiFi container started. This may take some time to start."
echo -e "      URL: ${CUrl}https://localhost:$PORT/nifi/${CNone}"
echo "Templates: ../etc/nifi"
echo ""
echo "Execute the following to get the generated user name and password from the log file."
echo "   docker logs nifi |grep -i generated"
