#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

HTTP_PORT=8089
HTTPS_PORT=8443


if [ ! -d $APP_DIR/padogrid/nifi/data ]; then
  mkdir -p $APP_DIR/padogrid/nifi/data/json
fi
docker run --rm -d --name nifi -p $HTTPS_PORT:8443 -p $HTTP_PORT:8080 \
  --network my_network \
  --volume $APP_DIR/padogrid:/padogrid/ \
  apache/nifi:latest

echo "NiFi container started. This may take some time to start."
echo -e "      URL: ${CUrl}http://localhost:$HTTP_PORT/nifi/${CNone}"
echo -e "      URL: ${CUrl}https://localhost:$HTTPS_PORT/nifi/${CNone}"
echo "Templates: ../etc/nifi"
echo ""
echo "For HTTPS, execute the following to get the generated user name and password from the log file."
echo "   docker logs nifi |grep -i generated"
